### ISSUE TITLE
Reason for the `text-domain`

### ISSUE THREAD

**Issue by vachan** [wpindiaorg/camptix-indian-payments#15]
To maintain uniformity of the code, it is suggested to keep the text-domain as the product any, as also the product name is neutral as the supported payments, one is a Gateway & the other is a Platform.

**Comment by vachan** [comment]
**Suggested:** `camptix-indian-payments`

**Comment by sanyogs** [comment]
Plugin slug CANNOT be "CampTix Indian Payment" (which would actually be camptix-indian payment) because we do not LEGALLY represent CampTix. This is something hope you understand

**Comment by vachan** [comment]
If you may read the title of the issue, I am asking about `text-domain` and not the slug.
also rather than a typo of _campt-_ it may be advised by the review to name it as **Indian Payments for CampTix**

**Comment by claudiosanches** [comment]
Text domain should be `campt-indian-payment-gateway` since is the slug on WordPress.org: https://wordpress.org/plugins/campt-indian-payment-gateway/

This should allow people to translate in https://translate.wordpress.org/projects/wp-plugins/campt-indian-payment-gateway

See https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains

> It’s important to use a text domain to denote all text belonging to that plugin. The text domain is a unique identifier, which makes sure WordPress can distinguish between all loaded translations. This increases portability and plays better with already existing WordPress tools. **The text domain must match the slug of the plugin. If your plugin is a single file called my-plugin.php or it is contained in a folder called my-plugin the domain name should be my-plugin. If your plugin is hosted on wordpress.org it must be the slug of your plugin URL (wordpress.org/plugins/{slug})**.
The text domain name must use dashes and not underscores.

**Comment by ravinderk** [comment]
Closing this issue because current text domain seems perfect.
